apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: project-webstack
type: Opaque
data:
  mariadb-root-password: cm9vdF80NTY=
  mariadb-password: d2Vic3RhY2tfOTg3
  mariadb-user: YWRtaW5fMTIz
