name: build image

permissions:
  id-token: write
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bl-api:${{ github.sha }} ./Webstack/api/

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bl-api:${{ github.sha }}

  build_frontend:
    runs-on: ubuntu-latest
    needs: build_api
    steps:
      - name: Checkout repository code into runner
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bl-frontend:${{ github.sha }} ./Webstack/frontend/

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/bl-frontend:${{ github.sha }}

      - name: Update Kubernetes manifest
        run: |
          # Vervang de versie-placeholders
          sed -i "s|VERSION_PLACEHOLDER|${{ github.sha }}|g" Webstack/k8s/base/api.yaml
          sed -i "s|VERSION_PLACEHOLDER|${{ github.sha }}|g" Webstack/k8s/base/frontend.yaml
          
          # Controleer of er daadwerkelijk wijzigingen zijn
          if [[ -n $(git status --porcelain) ]]; then
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git add Webstack/k8s/base/api.yaml Webstack/k8s/base/frontend.yaml
            git commit -m "Update images to version ${{ github.sha }}"
            git push
          else
            echo "Geen wijzigingen in de manifest-bestanden, overslaan van commit/push."
          fi